import { mkdirSync, writeFileSync, copyFileSync, readFileSync } from "node:fs";
import path from "node:path";

import { resolveDslPath, loadDsl } from "./loader.js";

/** Reads this package's own version so the generated Dockerfile pins it. */
function pkgVersion(): string {
  try {
    const raw = readFileSync(new URL("../package.json", import.meta.url), "utf8");
    return (JSON.parse(raw).version as string) || "latest";
  } catch {
    return "latest";
  }
}

export interface DeployOptions {
  file?: string;
  cwd?: string;
  out?: string;
  port?: number;
  compose?: boolean;
}

export interface DeployResult {
  outDir: string;
  files: string[];
}

/**
 * Generates a self-contained, Docker-ready bundle for the current mock.
 * Validates the DSL first, then writes a Dockerfile, .dockerignore, a copy of
 * the DSL as `mock-fast.json`, a README, and (optionally) a compose file.
 */
export async function runDeploy(opts: DeployOptions = {}): Promise<DeployResult> {
  const cwd = opts.cwd ?? process.cwd();
  const port = opts.port ?? 3001;
  const version = pkgVersion();

  // 1. Resolve + validate the DSL — fail fast on a broken mock.
  const absPath = await resolveDslPath(cwd, opts.file);
  await loadDsl(absPath); // throws LoaderError if invalid

  // 2. Prepare the output folder (named to avoid clashing with build `dist/`).
  const outDir = path.resolve(cwd, opts.out ?? "mock-deploy");
  mkdirSync(outDir, { recursive: true });

  // 3. Copy the DSL as mock-fast.json (auto-detected by the server).
  copyFileSync(absPath, path.join(outDir, "mock-fast.json"));

  // 4. Write the bundle files.
  const written: string[] = ["mock-fast.json"];
  const write = (name: string, content: string) => {
    writeFileSync(path.join(outDir, name), content);
    written.push(name);
  };

  write("Dockerfile", dockerfile(version, port));
  write(".dockerignore", dockerignore());
  write("README.md", readme(version, port));
  if (opts.compose) write("docker-compose.yml", compose(port));

  return { outDir, files: written };
}

function dockerfile(version: string, port: number): string {
  return `# Generated by \`mock-fast deploy\`.
# This is a MOCK server: no real auth (JWTs are NOT verified). Don't expose real data.
FROM node:20-alpine
WORKDIR /app
RUN npm install -g mock-fast@${version}
COPY mock-fast.json ./mock-fast.json
# HTTP port only. The admin API (3110) also starts but must NOT be exposed publicly.
EXPOSE ${port}
CMD ["mock-fast", "start", "--host", "0.0.0.0", "--port", "${port}", "--no-watch"]
`;
}

function dockerignore(): string {
  return `node_modules
npm-debug.log
.git
.DS_Store
`;
}

function compose(port: number): string {
  return `services:
  mock:
    build: .
    ports:
      - "${port}:${port}"
    restart: unless-stopped
`;
}

function readme(version: string, port: number): string {
  return `# mock-deploy — Docker bundle for your mock-fast server

Generated by \`mock-fast deploy\`. This folder is **self-contained**: it's everything
needed to ship the mock. The \`mock-fast.json\` carries its bodies inline, so no other
files (and not your \`api-spec/\`) are required.

## Build & run

\`\`\`bash
docker build -t my-mock .
docker run --rm -p ${port}:${port} my-mock
\`\`\`

Then hit \`http://localhost:${port}\`.

## What's here

- \`Dockerfile\` — pins \`mock-fast@${version}\`, binds \`0.0.0.0\`, disables hot reload.
- \`mock-fast.json\` — your DSL (the only thing the server needs).

## Important — it's a MOCK, not a real backend

- **No real security.** \`requireAuth\` only checks the header *pattern*; JWTs are **not**
  verified. Anyone with the URL can call it. Never put real or sensitive data behind it.
- **Admin API (port 3110)** also starts and can change routes at runtime. The Dockerfile
  does **not** expose it — keep it that way; never publish \`3110\` to the internet.
- **Rate-limit / lockout counters live in memory** — they reset on restart and are not
  shared across replicas. Run a single instance if that behavior matters.
- **No HTTPS.** Put it behind a reverse proxy or your platform's TLS.

## Deploy anywhere

Any host that runs containers (Render, Railway, Fly.io, Cloud Run, a VPS, …).
If the platform injects a \`$PORT\`, override the command:

\`\`\`bash
mock-fast start --host 0.0.0.0 --port $PORT --no-watch
\`\`\`
`;
}
